server:
  port: 8081
spring:
  application:
    name: mod-tlr
  datasource:
    username: ${DB_USERNAME:folio_admin}
    password: ${DB_PASSWORD:folio_admin}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
  sql:
    init:
      # to boot up application despite of any DB connection issues
      continue-on-error: true
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: POSTGRESQL
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  jackson:
    default-property-inclusion: non_empty
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
  mustache:
    check-template-location: false
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      key-store-password: ${KAFKA_SSL_KEYSTORE_PASSWORD:}
      key-store-location: ${KAFKA_SSL_KEYSTORE_LOCATION:}
      trust-store-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD:}
      trust-store-location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:}
    consumer:
      auto-offset-reset: latest
      group-id: ${ENV:folio}-mod-tlr-group
folio:
  tenant:
    validation:
      enabled: true
  environment: ${ENV:folio}
  okapi-url: ${OKAPI_URL:http://okapi:9130}
  system-user:
    enabled:  ${SYSTEM_USER_ENABLED:true}
    username: ${SYSTEM_USER_NAME:mod-tlr}
    password: ${SYSTEM_USER_PASSWORD:mod-tlr}
    lastname: System
    permissionsFilePath: permissions/mod-tlr.csv
  exchange:
    enabled: true # REQUIRED for HTTP service clients
  logging:
    # Levels:
    # NONE     No logging
    # BASIC    URI, HTTP method, status code, duration
    # HEADERS  BASIC + request and response headers
    # FULL     HEADERS + request and response bodies
    request:
      enabled: true # Optional, logs incoming HTTP requests
      level: BASIC # Optional
    exchange:
      enabled: true # Optional, logs outgoing HTTP client requests
      level: BASIC # Optional, default: BASIC
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace
      base-path: /admin
  #  endpoint:
  #    health:
  #      show-details: always
  #      show-components: always
  ###################################################
  # Disable all checks except for readiness
  ###################################################
  health:
    defaults:
      enabled: false
    readinessstate:
      enabled: true
debug: false
logging:
  level:
    org.folio.spring.filter.LoggingRequestFilter: DEBUG
    org.folio.spring.client.ExchangeLoggingInterceptor: DEBUG
