openapi: 3.0.0
info:
  title: ECS Loans API
  version: v1
tags:
  - name: ecsLoans
paths:
  /tlr/loans/check-out-by-barcode:
    post:
      operationId: checkOutByBarcode
      description: Checks item out by barcode
      tags:
        - ecsLoans
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/check-out-request"
        required: true
      responses:
        '200':
          $ref: "#/components/responses/checkOutResponse"
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '422':
          $ref: '#/components/responses/unprocessableEntityResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /tlr/loans/declare-item-lost:
    post:
      operationId: declareItemLost
      description: Declare item lost
      tags:
        - ecsLoans
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/declareItemLostRequest"
        required: true
      responses:
        '204':
          description: Item successfully declared lost
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '422':
          $ref: '#/components/responses/unprocessableEntityResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /tlr/loans/claim-item-returned:
    post:
      operationId: claimItemReturned
      description: Claim item returned
      tags:
        - ecsLoans
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/claimItemReturnedRequest"
        required: true
      responses:
        '204':
          description: Item successfully claimed returned
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '422':
          $ref: '#/components/responses/unprocessableEntityResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
components:
  schemas:
    check-out-request:
      $ref: 'schemas/circulation/check-out-request.yaml'
    check-out-dry-run-request:
      $ref: 'schemas/circulation/check-out-dry-run-request.yaml'
    check-out-dry-run-response:
      $ref: 'schemas/circulation/check-out-dry-run-response.yaml'
    loan-policy:
      $ref: 'schemas/circulation-storage/loan-policy.json'
    errorResponse:
      $ref: 'schemas/errors.json'
    consortiumItems:
      $ref: 'schemas/search/consortiumItems.yaml'
    searchBatchIds:
      $ref: 'schemas/search/batchIds.yaml'
    declareItemLostRequest:
      $ref: 'schemas/circulation/declare-item-lost-request.yaml'
    claimItemReturnedRequest:
      $ref: 'schemas/circulation/claim-item-returned-request.yaml'
  responses:
    checkOutResponse:
      description: Check out response
      content:
        application/json:
          schema:
            $ref: 'schemas/circulation/check-out-response.yaml'
    badRequestResponse:
      description: Validation errors
      content:
        application/json:
          example:
            errors:
              - message: Request is invalid
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
    notFoundResponse:
      description: Not found
      content:
        application/json:
          example:
            errors:
              - message: Request not found
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
    unprocessableEntityResponse:
      description: Validation errors
      content:
        application/json:
          example:
            errors:
              - message: Request is invalid
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerErrorResponse:
      description: When unhandled exception occurred during code execution, e.g. NullPointerException
      content:
        application/json:
          example:
            errors:
              - message: Unexpected error
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
