openapi: 3.0.0
info:
  title: ECS TLR API
  version: v1
paths:
  /tlr/ecs-tlr:
    post:
      description: Create ECS TLR
      operationId: postEcsTlr
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ecs-tlr"
        required: true
      responses:
        '201':
          $ref: "#/components/responses/ecs-tlr"
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /tlr/ecs-tlr/{requestId}:
    get:
      description: Retrieve ECS TLR by ID
      operationId: getEcsTlrById
      parameters:
        - $ref: '#/components/parameters/requestId'
      responses:
        '200':
          $ref: '#/components/responses/ecs-tlr'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    put:
      description: Update ECS TLR by ID
      operationId: putEcsTlrById
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ecs-tlr"
        required: true
      parameters:
        - $ref: '#/components/parameters/requestId'
      responses:
        '204':
          description: Request successfully updated
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    delete:
      description: Remove ECS TLR by ID
      operationId: deleteEcsTlrById
      parameters:
        - $ref: '#/components/parameters/requestId'
      responses:
        '204':
          description: Request successfully removed
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
components:
  schemas:
    ecs-tlr:
      $ref: 'schemas/EcsTlr.yaml#/EcsTlr'
    dcbTransaction:
      $ref: 'schemas/dcbTransaction.yaml#/DcbTransaction'
    transactionStatus:
      $ref: 'schemas/transactionStatus.yaml#/TransactionStatus'
    transactionStatusResponse:
        $ref: 'schemas/transactionStatusResponse.yaml#/TransactionStatusResponse'
    errorResponse:
      $ref: 'schemas/errors.json'
    request:
      $ref: 'schemas/request.json'
    searchInstancesResponse:
      $ref: schemas/response/searchInstancesResponse.json
    user:
      $ref: schemas/user.json
  parameters:
    requestId:
      name: requestId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  responses:
    ecs-tlr:
      description: ECS TLR object
      content:
        application/json:
          schema:
            $ref: 'schemas/EcsTlr.yaml#/EcsTlr'
    badRequestResponse:
      description: Validation errors
      content:
        application/json:
          example:
            errors:
              - message: Request is invalid
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
    notFoundResponse:
      description: Not found
      content:
        application/json:
          example:
            errors:
              - message: Request not found
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerErrorResponse:
      description: When unhandled exception occurred during code execution, e.g. NullPointerException
      content:
        application/json:
          example:
            errors:
              - message: Unexpected error
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
