openapi: 3.0.0
info:
  title: ECS TLR API
  version: v1
paths:
  /tlr/ecs-tlr:
    post:
      description: Create ECS TLR
      operationId: postEcsTlr
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ecs-tlr"
        required: true
      responses:
        '201':
          $ref: "#/components/responses/ecs-tlr"
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
  /tlr/ecs-tlr/{requestId}:
    get:
      description: Retrieve ECS TLR by ID
      operationId: getEcsTlrById
      parameters:
        - $ref: '#/components/parameters/requestId'
      responses:
        '200':
          $ref: '#/components/responses/ecs-tlr'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          description: Not found
          content:
            text/plain:
              schema:
                type: string
                example: Not found
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
components:
  schemas:
    ecs-tlr:
      $ref: 'schemas/EcsTlr.yaml#/EcsTlr'
    errorResponse:
      $ref: 'schemas/errors.json'
    request:
      $ref: 'schemas/request.json'
  parameters:
    requestId:
      name: requestId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  responses:
    ecs-tlr:
      description: ECS TLR object
      content:
        application/json:
          schema:
            $ref: 'schemas/EcsTlr.yaml#/EcsTlr'
    badRequestResponse:
      description: Validation errors
      content:
        application/json:
          example:
            errors:
              - message: Request is invalid
                code: invalid.request
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerErrorResponse:
      description: When unhandled exception occurred during code execution, e.g. NullPointerException
      content:
        application/json:
          example:
            errors:
              - message: Unexpected error
                code: unexpected.error
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
