openapi: 3.0.0
info:
  title: ECS Request External API
  version: v1
tags:
  - name: ecsRequestExternal
paths:
  /tlr/create-ecs-request-external:
    post:
      description: Create ECS request external
      operationId: postEcsRequestExternal
      tags:
        - ecsRequestExternal
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ecs-request-external"
        required: true
      responses:
        '201':
          $ref: "#/components/responses/ecs-tlr"
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
components:
  schemas:
    ecs-request-external:
      $ref: 'schemas/EcsRequestExternal.yaml#/EcsRequestExternal'
    errorResponse:
      $ref: 'schemas/errors.json'
  responses:
    ecs-tlr:
      description: ECS TLR object
      content:
        application/json:
          schema:
            $ref: 'schemas/EcsTlr.yaml#/EcsTlr'
    badRequestResponse:
      description: Validation errors
      content:
        application/json:
          example:
            errors:
              - message: Request is invalid
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerErrorResponse:
      description: When unhandled exception occurred during code execution, e.g. NullPointerException
      content:
        application/json:
          example:
            errors:
              - message: Unexpected error
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
