openapi: 3.0.0
info:
  title: TLR Settings API
  version: v1
tags:
  - name: tlrSettings
paths:
  /tlr/settings:
    get:
      description: Retrieve TLR Settings
      operationId: getTlrSettings
      tags:
        - tlrSettings
      responses:
        '200':
          $ref: '#/components/responses/tlr-settings'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
    put:
      description: Update TLR Settings
      operationId: putTlrSettings
      tags:
        - tlrSettings
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tlr-settings"
        required: true
      responses:
        '204':
          description: Request successfully updated
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '404':
          $ref: '#/components/responses/notFoundResponse'
        '500':
          $ref: '#/components/responses/internalServerErrorResponse'
components:
  schemas:
    tlr-settings:
      $ref: 'schemas/TlrSettings.yaml#/TlrSettings'
    errorResponse:
      $ref: 'schemas/errors.json'
  responses:
    tlr-settings:
      description: TLR Settings
      content:
        application/json:
          schema:
            $ref: 'schemas/TlrSettings.yaml#/TlrSettings'
    badRequestResponse:
      description: Validation errors
      content:
        application/json:
          example:
            errors:
              - message: Request is invalid
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
    notFoundResponse:
      description: Not found
      content:
        application/json:
          example:
            errors:
              - message: Request not found
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
    internalServerErrorResponse:
      description: When unhandled exception occurred during code execution, e.g. NullPointerException
      content:
        application/json:
          example:
            errors:
              - message: Unexpected error
            total_records: 1
          schema:
            $ref: "#/components/schemas/errorResponse"
