package org.folio.domain.type;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
  ECS_REQUEST_CANNOT_BE_PLACED_FOR_INACTIVE_PATRON(
    "ECS_REQUEST_CANNOT_BE_PLACED_FOR_INACTIVE_PATRON"),
  LOAN_NOT_FOUND("LOAN_NOT_FOUND"),
  PATRON_HAS_OPEN_ECS_TLR_FOR_THE_SAME_TITLE("PATRON_HAS_OPEN_ECS_TLR_FOR_THE_SAME_TITLE"),
  INVALID_LOAN_ACTION_REQUEST("INVALID_LOAN_ACTION_REQUEST"),
  METHOD_ARGUMENT_NOT_VALID("METHOD_ARGUMENT_NOT_VALID"),
  INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR");

  private final String value;
}
