package org.folio.support;

import org.apache.commons.lang3.StringUtils;

import lombok.experimental.UtilityClass;
import lombok.extern.log4j.Log4j2;

@Log4j2
@UtilityClass
public class BarcodeUtil {

  public static String buildNonEmptyBarcode(String barcode, String itemId) {
    if (StringUtils.isBlank(barcode)) {
      log.info("buildNonEmptyBarcode:: barcode is null or empty, using autogenerated barcode: {}",
        itemId);
      return itemId;
    }

    return barcode;
  }

}
